### ISSUE TITLE
Edit a listing

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#104]
## Description
As the owner of a given listing\
I want to update a listing\
so that I can change/correct/add any information I wish.

## Acceptance Criteria
- User must be logged in
- User must own the listing
- User must complete all mandatory fields

## Dev tasks
- [x] [Create frontend component to edit a listing](https://github.com/gilhrpenner/COMP4350/issues/123)
- [x] [Create backend endpoint to consume those changes](https://github.com/gilhrpenner/COMP4350/issues/98)

Story points: 2/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Edit a listing
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. If you do not have any listings, follow the “create a new listing” steps to add a listing to your account.
4. Once signed in and on the dashboard page, click on the pencil icon button on one of your listings to open the listing in the listing editor page.
5. Enter a different value for the listing title field (example value: `My edit test title`).
6. Enter a different value for the price field (example value: `123.00`).
7. Select a different condition from the condition dropdown. (example value: `Used - Good`).
8. Select a different status from the status dropdown (example value: `Available`).
9. Enter a different value for the description field (example value: `This is a test description that has been edited`).
10. If your listing had a photo added to it, hover over the image in the preview on the right side and click the delete button to remove it.
11. Click on the gray box under “Select item photos” to open the file browser to select and upload a different .jpg, .jpeg, or .png image file. Note: You can select more than one photo to upload.
12. Click the edit listing button to save your changes and navigate back to the dashboard page.
