### ISSUE TITLE
View all own listings

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#105]
## Description
As a registered user and owner of one or multiple listings\
I want to view all my listings\
so that I can view or change status of multiple listings at once

## Acceptance Criteria
- User must be logged in
- User must own the listings
- User must have at least one (1) listing available

## Dev tasks
- [x] [Create frontend component to display all listings](https://github.com/gilhrpenner/COMP4350/issues/124)
- [x] [Create backend endpoint to fetch and return all listings from a userId](https://github.com/gilhrpenner/COMP4350/issues/98)

Story points: 2/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

View all my own listings
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. If you do not have any listings, follow the “create a new listing” steps to add multiple listings to your account.
4. If not on the dashboard, click the button on the navigation bar that has the user’s name in it to go to the dashboard.
5. Once signed in and on the dashboard page, you should be able to see all of your created listings.
6. Click on the paper with an eye icon button on any of your listings to open a preview dialog window which displays the listing information.
