### ISSUE TITLE
Delete a listing

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#106]
## Description
As the owner of the listing\
I want to delete the listing\
so that no one else can see or make offers to it.

## Acceptance Criteria
- User must be logged in
- User must own the listing
- User must confirm a "warning" dialog indicating there is no coming back.

## Dev tasks
- [x] [Create frontend component to delete a listing](https://github.com/gilhrpenner/COMP4350/issues/125)
- [x] [Create backend endpoint to delete one or multiple listings](https://github.com/gilhrpenner/COMP4350/issues/98)

Story points: 3/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Delete a listing
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. If you do not have any listings, follow the “create a new listing” steps to add a listing to your account.
4. If not on the dashboard, click the button on the navigation bar that has the user’s name in it to go to the dashboard.
5. Once signed in and on the dashboard page, click the garbage bin icon button to open a confirmation dialog.
6. Click delete to delete your listing. A notification will appear stating that your listing was deleted successfully. The listing will be removed from the dashboard as well.
