### ISSUE TITLE
Update multiple listings status

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#107]
## Description
As a registered user\
I want to edit multiple listing status\
so that I can indicate product's availability

## Acceptance Criteria
- User must be logged in
- User can only edit listings that they own

## Dev tasks
- [x] Will use same component as story `View all own listings`
- [x] [Create endpoint to apply changes to all selected listings](https://github.com/gilhrpenner/COMP4350/issues/98)

Story points: 1/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Update multiple listings’ statuses
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. If you do not have any listings, follow the “create a new listing” steps to add multiple listings to your account.
4. If not on the dashboard, click the button on the navigation bar that has the user’s name in it to go to the dashboard.
5. Once signed in and on the dashboard page, click the manage multiple listings button to open a listings manager dialog.
6. Select multiple listings using the checkboxes on the left of the dialog.
7. Select a listing status via the “Update listings status” dropdown. A notification should appear stating that the listings’ status was updated. The status column on the dialog table should also reflect those changes.
8. With those listings still selected, click the delete <number> listings button to delete the selected listings. A notification should appear stating the listings were deleted successfully.
9. Click off the dialog to close it. The listings that were selected should no longer be in the dashboard as they were deleted.
