### ISSUE TITLE
Edit my account details

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#108]
## Description
As a registered user\
I want to edit my account details\
so that I can change password, profile picture, etc.

## Acceptance Criteria
- User must be registered
- User must be logged in
- User must fill all required fields

## Dev tasks
- [x] [Create frontend component to view/edit account details](https://github.com/gilhrpenner/COMP4350/issues/126)
- [ ] [Create backend endpoint to consume those changes](https://github.com/gilhrpenner/COMP4350/issues/127)

Story points: 2/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Edit my account details
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. Once signed in and on the dashboard page, click on the account tab on the left drawer to
navigate to the account section.
4. Upload a .jpeg, .jpeg, or .png image for the account’s banner by clicking on the first
upload button.
5. Upload a .jpeg, .jpeg, or .png image for the account’s profile picture by clicking on the
second upload button.
6. Enter a different value into the first name field.
7. Enter a different value into the last name field.
8. Fill in the facebook field with a valid URL or enter a different valid URL if your account
has that field already filled in (example value: https://facebook.com/test).
9. Fill in the instagram field with a valid URL or enter a different valid URL if your account
has that field already filled in (example value:https://instagram.com/test).
10. Fill in the twitter field with a valid URL or enter a different valid URL if your account
has that field already filled in (example value: https://twitter.com/test).
11. Fill in the personal website field with a valid URL or enter a different valid URL if your
account has that field already filled in (example value: https://selloff.tech).
12. Click on the save changes button to save your account information and a notification
should appear stating that the general information was updated.
13. Refresh the page and the details you had saved should still be in the fields and in the
image previews.
