### ISSUE TITLE
View an individual listing

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#109]
## Description
As a user\
I want to view a listing\
so that I can see the details and pictures of a listing.

## Acceptance Criteria
- User does not need to be registered to view a listing
- Guest users cannot message the listing owner

## Dev tasks
- [x] Create frontend component to display a listing
- [x] [Create backend endpoint to fetch the details from a listing](https://github.com/gilhrpenner/COMP4350/issues/98)
- [x] Fetch/serve listing images (if applicable) from S3

Story points: 4/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

View an individual listing
1. Go to the homepage of the application.
2. Select a listing via one of methods:
    a. Click one of the listings on the home page
    b. Click on a category to open the browsing page, then click on a listing.
3. Once you have selected a listing, it should navigate you to a listing page. On the listing page, there should be details like the listing title, price, category, creation date/time, condition, and description.
