### ISSUE TITLE
Log in with account

### ISSUE THREAD

**Issue by BrettDowneyuofm** [gilhrpenner/COMP4350#11]
### Description:
As a returning seller/buyer (with an existing account), I should be able to log into the website so that I can access the application using my specific account. 

### Acceptance Criteria:
Given that I am a user on the login page that has already registered an account
When I attempt to login using my chosen identifier and password
Then I should be redirected to the home view after successfully signing in and can then use features which require an account such as creating listings and messaging other users

### Dev Tasks:
[Setup REST API](https://github.com/gilhrpenner/COMP4350/issues/45)
[Transferring Account Details](https://github.com/gilhrpenner/COMP4350/issues/37)
[Load data related to account](https://github.com/gilhrpenner/COMP4350/issues/44)
[Login UI](https://github.com/gilhrpenner/COMP4350/issues/47)

### Story Points (1-5): 3

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Sign in with an account
1. If you do not have an account, follow the “create an account” steps.
2. Go to the homepage of the application by clicking on the SellOff logo on the navigation bar.
3. Click the sign in button to go to the sign in page.
4. Type in the email of your already existing account.
5. Type in the password of your already existing account.
6. Click on the sign in button to sign in and redirect to the dashboard page.
    a. If the input values to the email or password were not valid (refer to create an account’s steps 6 and 7), you will not be able to submit the form and invalid fields will be highlighted red.
    b. If the password and username are valid but do not match an existing account, a notification will appear saying the email or password is invalid and the page will remain on the sign in page.
