### ISSUE TITLE
Follow users

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#110]
## Description
As a registered user\
I want to follow a user\
so that I can easily find them and see their listings.

## Acceptance Criteria
- User must be logged in
- User must be able to unfollow the user

## Dev tasks
- [ ] Add a follow button on users postings/profiles
- [x] Create backend endpoint to consume those changes

Story points: 1/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Follow users
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. Once signed in and on the dashboard page, click on the logo on the navigation bar to go to the homepage.
4. Select a listing on the homepage to go to the listing’s page.
a. Alternatively, could click on the search button to go to the browsing page, then click on a listing to go to the listing’s page.
5. Click on the follow seller button on the right side of the page to follow the user. The follow seller button should now be the unfollow seller button. A notification should appear stating that a user has been added to your following list.
6. Refresh the page and the button should still be the unfollow seller button.
7. Click the unfollow seller button to unfollow the seller. The unfollow seller button should now be the follow seller button. A notification should appear stating that a user has been removed from your following list.
8. Click on the listing creator’s name to go to the user’s page. The button on the right side of the screen should be the follow seller button.
9. Click on the follow seller button on the right side of the user page to follow the user. The follow seller button should now be the unfollow seller button. A notification should appear stating that a user has been added to your following list.
10. Refresh the page and the button should still be the unfollow seller button.
