### ISSUE TITLE
Manage followed users

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#111]
## Description
As a registered user\
I want to to manage all users I follow\
so that I can easily find them and unfollow

## Acceptance Criteria
- User must be logged in
- User can only see its own following list

## Dev tasks
- [ ] On frontend, add tab/button/menu in the user's profile
- [x] Create backend endpoint to consume those changes

Story points: 2/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Manage my followed users
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. If your account is not following any users, follow steps 3-5 of the “follow users” steps to follow some users.
4. If not on the dashboard, click the button on the navigation bar that has the user’s name in it to go to the dashboard.
5. Click on the followed users option on the left drawer to go to the followed users section. You should see a list of all the users you follow.
6. Click on any of the users in the list to navigate to their user page.
7. Click the unfollow seller button to unfollow the seller. The unfollow seller button should now be the follow seller button. A notification should appear stating that a user has been removed from your following list.
8. Navigate back to the followed users section of the dashboard (click the browser back button).
9. The user which you unfollowed will no longer be on the page.
