### ISSUE TITLE
See all listings from a followed user

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#112]
## Description
As a registered user\
I want to see all listings from another user I follow\
so that I can keep track of what they sell.

## Acceptance Criteria
- User must be logged in
- User can only see all listings from users they follow

## Dev tasks
- [ ] On frontend, add button (when managing list of followed users) to see their listings

Story points: 2/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

See all listings from a followed user
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. If your account is not following any users, follow steps 3-5 of the “follow users” steps to follow some users.
4. If not on the dashboard, click the button on the navigation bar that has the user’s name in it to go to the dashboard.
5. Click on the followed users option on the left drawer to go to the followed users section. You should see a list of all the users you follow.
6. Click on any of the users in the list to navigate to their user page.
7. Once on the user page, you will be able to see the user’s listings.
