### ISSUE TITLE
Favorite a listing

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#113]
## Description
As a registered user\
I want to favorite a listing\
so that I can easily find at a later date/time

## Acceptance Criteria
- User must be logged in

## Dev tasks
- [x] On frontend, create a button in a listing so users can favorite it
- [x] Create a backend endpoint to favorite a listing
- [x] Create a table for favorite listings

Story points: 4/5

Done under https://github.com/gilhrpenner/COMP4350/issues/111!

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Favorite a listing on my account
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. Go to the homepage of the application by clicking on the SellOff logo on the navigation bar.
4. Scroll down and there will be randomly selected categories and listings displayed on the home page.
5. Click on one of the listings. It should navigate you to the appropriate listing page.
6. Click the bookmark icon button (beside the share icon button and price) to favorite the listing. A notification should appear stating that a listing has been added to your favorites, and the button should get filled in.
7. Refresh the page.
8. The bookmark icon button should be filled in, indicating the listing is favorited.
