### ISSUE TITLE
Manage favorite listing

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#114]
## Description
As a registered user\
I want to see all favorite listings\
so that I can manage them to see, unfavorite, share.

## Acceptance Criteria
- User must be logged in
- User can only see listings they favorited
- If a listing is no longer available, remove from the list

## Dev tasks
- [x] #223
- [x] #197 

Story points: 3/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Tests

Manage my favorite listings on my account
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. If you do not have multiple favorite listings on your account, repeat steps 3-6 from the “favorite a listing on my account” steps until you have added a few listings to your favorites.
4. If not on the dashboard, click the button on the navigation bar that has the user’s name in it to go to the dashboard.
5. Click on the favorite listings option on the left drawer to go to the favorite listings section. You should see a list of all the listings you have favorited.
6. Click on the first listing to confirm it navigates you to the appropriate listing page.
7. Go back on the browser to return to the favorite listings section.
8. Click on the bookmark icon button on one of the listings to unfavorite it. A notification should appear stating you have removed a listing from your favorites. The listing should also be removed from the favorite listings section.
