### ISSUE TITLE
Filter listings

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#115]
## Description
As a user\
I want to I want to filter listings according to price, owners, etc\
so that easily find what I am looking for.

## Acceptance Criteria
- User does not need to be logged in (guest user)

## Dev tasks
- [ ] Create frontend component to filter listings
- [x] [Create initial backend routes for getting search results](https://github.com/gilhrpenner/COMP4350/issues/178)
- [x] [Create initial frontend route and component(s) for browsing search results](https://github.com/gilhrpenner/COMP4350/issues/181)

Story points: 3/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Filter listings
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. If you do not have any listings, follow the “create a new listing” steps to add a listing to your account. Ensure it has a price of $100.
4. Go to the homepage of the application by clicking on the SellOff logo on the navigation bar.
5. Click on the search button to enter the browsing screen. The results should include every listing with no filtering applied. No province should be selected from the dropdown and no specific category should be selected.
6. Select the category of the previously created listing from the category dropdown.
7. Click the search button to apply the changes. The results should be filtered by the category.
8. Verify the results are filtered by category:
    a. Click on a listing from the results.
    b. Verify the category on the listing page matches the filtered category.
    c. Click on the back button to return to search results.
    d. Repeat steps 8a to 8c for two additional listings to ensure they are filtered by category.
9. Select “all categories” from the category dropdown.
10. Click the search button to remove the filtering by category.
11. Click on the filter button to open the filtering menu.
12. Fill in the min price field with 99 (recall this is $1 lower than your created listing).
13. Click apply to get the filtered results.
14. Verify the results are filtered by min price by scrolling through to results to ensure no prices are lower than $99.
15. Click on the filter button to open the filtering menu.
16. Click reset to remove the min price filter. The result should now include listings with prices of $99 and below.
17. Click on the filter button to open the filtering menu.
18. Fill in the max price field with 101 (recall this is $1 higher than your created listing).
19. Click apply to get the filtered results.
20. Verify the results are filtered by max price by scrolling through to results to ensure no prices are higher than $101.
21. Click on the filter button to open the filtering menu.
22. Click reset to remove the max price filter. The result should now include listings with prices of $101 and higher.
23. Click on the filter button to open the filtering menu.
24. Select the condition that matches your created listing from the condition dropdown.
25. Click apply to get the filtered results.
26. Verify the results are filtered by condition:
    a. Click on a listing from the results.
    b. Verify the condition on the listing page matches the filtered condition.
    c. Click on the back button to return to search results.
    d. Repeat steps 26a to 26c for two additional listings (if possible) to ensure they are filtered by condition.
27. Click on the filter button to open the filtering menu.
28. Click reset to remove the condition filter. The result should now include listings with any condition.
29. Select the province of your created listing from the province dropdown.
30. Click the search button to apply the changes. The results should now be filtered by province.
31. Verify the results are filtered by province by scrolling through to results to ensure no locations are outside of the selected province.
32. Now, apply all of those previously used filters at once:
    a. Select the category of the previously created listing you created from the category dropdown.
    b. Click the search button to apply the category filter and keep the province filter.
    c. Click on the filter button to open the filtering menu.
    d. Select the condition that matches your created listing from the condition dropdown.
    e. Fill in the min price field with 99 (recall this is $1 lower than your created listing).
    f. Fill in the max price field with 101 (recall this is $1 higher than your created listing).
    g. Click apply to get the filtered results.
33. Scroll until you find your created listing. Given the specificity of the filters, it should be one of the first results.
