### ISSUE TITLE
Search listings by keywords or terms

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#116]
## Description
As a user\
I want to search for listings that have a keyword/term\
so that I can narrow down my searches.

## Acceptance Criteria
- User does not need to be logged in (guest user)
- If no listings matches the keywords, display a message with a sad face

## Dev tasks
- [x] [Create initial backend routes for getting search results](https://github.com/gilhrpenner/COMP4350/issues/178)
- [x] [Create initial frontend route and component(s) for browsing search results](https://github.com/gilhrpenner/COMP4350/issues/181)
- [x] Implement full-text search using Prisma

Story points: 5/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Search listings by words or phrases
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. If you do not have any listings, follow the “create a new listing” steps to add a listing to your account. Make sure it has a very specific key term in the title with other common words (e.g., `SellOff test for sale`) and another specific key term with other common words in the description (e.g., `Syntax Overflow good condition`).
4. Go to the homepage of the application by clicking on the SellOff logo on the navigation bar.
5. Click the search button to navigate to the browsing page.
6. Fill in the “search for anything” field with your created listing’s title.
7. Click the search button to apply the search query. The number of results should be reduced from the previous results.
8. Add quotation marks around your search query in the search for anything field.
9. The results should be reduced even further to only include listings that have your listing’s exact title in its title or description.
10. Erase the search for anything field.
11. Click search to get all listing results again.
12. Fill in the “search for anything” field with your created listing’s description.
13. Click the search button to apply the search query. The number of results should be reduced from the previous results.
14. Add quotation marks around your search query in the search for anything field.
15. The results should be reduced even further to only include listings that have your listing’s exact description in its title or description.
