### ISSUE TITLE
Sort listings

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#117]
## Description
As a user\
I want to sort listings\
so that I can easily find what I need.

## Acceptance Criteria
- User does not need to be logged in (guest user)

## Dev tasks
- [x] [Create initial backend routes for getting search result](https://github.com/gilhrpenner/COMP4350/issues/178)
- [x] [Create initial frontend route and component(s) for browsing search results](https://github.com/gilhrpenner/COMP4350/issues/181)
- [ ] Create frontend component to sort listings

Story points: 3/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Sort listings
1. Go to the homepage of the application.
2. Select a category from the homepage to enter the browsing page.
3. Verify the results are sorted by default with newest listings first:
    a. Click on the first listing from the results.
    b. Take a note of the created date on the listing’s page.
    c. Click on the back button to return to search results.
    d. Scroll down and click on a result further down the list.
    e. Take a note of the created date on the listing’s page. It should be older than the first listing.
    f. Click on the back button to return to search results.
4. Select oldest first from the sort by dropdown.
5. Verify the results are sorted with oldest listings first:
    a. Click on the first listing from the results.
    b. Take a note of the created date on the listing’s page.
    c. Click on the back button to return to search results.
    d. Scroll down and click on a result further down the list.
    e. Take a note of the created date on the listing’s page. It should be newer than the first listing.
    f. Click on the back button to return to search results.
6. Select lowest price from the sort by dropdown.
7. Verify the results are sorted with lowest priced listings first:
    a. Scroll through results
    b. Make sure that every subsequent listing will either have the same price or higher.
8. Select highest price from the sort by dropdown.
9. Verify the results are sorted with highest priced listings first:
    a. Scroll through results
    b. Make sure that every subsequent listing will either have the same price or lower.
