### ISSUE TITLE
Start a new conversation

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#118]
## Description
As a registered user\
I want to start a new conversation with another user\
so that I can low-ball them and piss them off.

## Acceptance Criteria
- User must be logged in
- User must view an active listing in order to see the message button
- The first message sent will need to contain a link and listing data such as name and price

## Dev tasks
- [ ] Create backend socket.io service
- [ ] Create a messages table
- [ ] Create a frontend component to send a message

Story points: 5/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Start a new conversation
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. Go to the homepage of the application by clicking on the SellOff logo on the navigation bar.
4. Scroll down and there will be randomly selected categories and listings displayed on the home page.
5. Click on one of the listings. It should navigate you to the appropriate listing page.
6. Click on the contact seller option on the right side of the screen to open up an expanded panel for messaging.
7. Fill in the “your message” field with a message to send.
8. Click on the send button. A notification should appear stating that your message has been submitted. The message you filled in should also be cleared as well.
