### ISSUE TITLE
View and manage conversations

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#119]
## Description
As a registered user\
I want to view all my conversations\
so that I can manage go onto them to see and respond to messages with another user.

## Acceptance Criteria
- User must be logged in
- User can only see conversations they are part of

## Dev tasks
- [ ] Create frontend component to display those conversations
- [ ] Create backend endpoint to fetch all conversations a user is part of

Story points: 4/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

View and manage conversations
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. If you have not sent any messages to anyone yet, follow steps 3-8 of the “start a new conversation” steps to message a few people.
4. If not on the dashboard, click the button on the navigation bar that has the user’s name in it to go to the dashboard.
5. Click on the messages tab on the left drawer to navigate to the messages section. There should be a list of conversations you have started on the left panel of the messages section.
6. Click on a conversation in the list. This should open up the conversation panel and should have your message history displayed within.
7. Fill in the “Enter a message” field with some text.
8. Click the send icon to send the message. Your message should show up in the conversation
9. Fill in the “Enter a message” field with some more text.
10. Hit the enter key while in the field to send a message. Your message should show up in the conversation.
11. Click the “…” button to open up that conversation’s options.
12. Click the delete conversation button to open up a confirmation window.
13. Click the delete button to confirm this. The conversation should get cleared out and removed from the conversation list. A notification should appear stating that the messages were deleted.
