### ISSUE TITLE
Receive notification for a new message

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#120]
## Description
As a logged-in user\
I want to receive a notification\
so that I know when I received a new message.

## Acceptance Criteria
- User must be logged in
- Notification icon/sound must be displayed/played when new message is received

## Dev tasks
- [ ] Create frontend component to display icon
- [ ] Create backend socket.io emit/room to communicate with the frontend.

Story points: 3/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Receive notifications for new messages
1. If you do not have an account, follow the “create an account” steps. For the rest of these steps we will refer to this as account A.
2. Create a second account using the “create an account” steps. For the rest of these steps we will refer to this as account B.
3. If you are not logged into account A, follow the “sign in with an account” steps.
4. Follow the “create a new listing” steps to add a listing to your account with a very specific searchable title (example value: `Messaging test for account A`).
5. In a second web browser, log into account B using the “sign in with account” steps.
6. With account B, go to the homepage of the application by clicking on the SellOff logo on the navigation bar.
7. With account B, fill in the “search for anything” field with the title in quotes of the newly created listing that was made using account A (example value: `”Messaging test for account A”`).
8. With account B, click the search button. This will navigate to the browsing page and will load in the results, which likely is only the one listing by account A.
9. With account B, click on the listing you created as account A to get to the listing page.
10. Click on the contact seller option on the right side of the screen to open up an expanded panel for messaging.
11. With account B, fill in the “your message” field with a message to send to account A
12. With account B, click on the send button. A notification should appear stating that your message has been submitted. The message you filled in should also be cleared as well. In the web browser with account A, a notification should appear stating that you received a new message (as long as you are not in the messaging page). The button on the navigation bar that has the account A’s name in it should have a red badge indicating a new message was received.
13. With account A, if not on the dashboard, click the button on the navigation bar that has the user’s name in it to go to the dashboard. The messages icon on the left drawer should have a ! in the icon.
14. With account A, click on the messages tab on the left drawer to navigate to the messages section. There should be a conversation with account B in the conversation list with a red “new” icon.
15. With account A, click on the conversation with account B to open it. This should remove the “new” icon from the conversation, the ! in the left drawer’s messages icon, and the red badge on the navigation bar.
