### ISSUE TITLE
Make an offer on a listing

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#121]
## Description
As a logged-in user\
I want to make an offer to a listing\
so that I can attempt to buy an item.

## Acceptance Criteria
- User must be logged-in
- Offer will be sent via chat

## Dev tasks
- [ ] Create frontend button to be displayed while viewing a listing

Story points: 2/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Make an offer on a listing
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. Go to the homepage of the application by clicking on the SellOff logo on the navigation bar.
4. Scroll down and there will be randomly selected categories and listings displayed on the home page.
5. Click on one of the listings. It should navigate you to the appropriate listing page.
6. Click on the contact seller option on the right side of the screen to open up an expanded panel for messaging.
7. Fill in the offer field with a number.
8. Click on the send icon button within the input field. A notification should appear stating that your message has been submitted. The offer you filled in should also be cleared as well.
