### ISSUE TITLE
View listings on home page

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#195]
## Description
As a user\
I want to see listings and their categories on the home page\
so that I can browse by category

## Acceptance Criteria
- Listings should be displayed by category
- Only a few listings should be loaded, once the user scrolls through them, load more

## Dev tasks
- [x] Endpoint to fetch all listings by category
- [x] Endpoint to request listings by category and pagination

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

View listings on home page
1. Go to the homepage of the application.
2. Scroll down and there will be randomly selected categories and listings displayed on the home page.
3. Click on one of the listings. It should navigate you to the appropriate listing page to get more details
