### ISSUE TITLE
Create an account

### ISSUE THREAD

**Issue by BrettDowneyuofm** [gilhrpenner/COMP4350#5]
### Description:
As a seller/buyer, I want to create an account so that I can create listings for things I want to sell, message sellers, and more.  

### Acceptance Criteria:
Given that I am an unregistered user on the website in the create account view
When I attempt to create an account using an identifier and password that has not been used before
Then I should be logged into the new account and can then use features which require an account such as creating listings and messaging other users

### Dev Tasks:
[Setup Database](https://github.com/gilhrpenner/COMP4350/issues/33)
[Setup Database Schema](https://github.com/gilhrpenner/COMP4350/issues/35)
[Setup REST API](https://github.com/gilhrpenner/COMP4350/issues/45)
[Transferring Account Details](https://github.com/gilhrpenner/COMP4350/issues/37)
[User Interface](https://github.com/gilhrpenner/COMP4350/issues/49)

### Story Points (1-5): 3

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Create an account:
1. Go to the homepage of the application.
2. Click the sign in button to go to the sign in page.
3. Click on “Sign up for free” to go to the create account page.
4. Fill in the first name field (example value: `Mark`).
5. Fill in the last name field (example value: `Robitaille`).
6. Fill in the email address field with a valid email (example value:
`robitai4@myumanitoba.ca`)
7. Fill in the password field with a password longer than 6 characters that contains an
uppercase character, a lowercase character, a number and a special character (example
value: `Test_123`).
8. Click on the create account button to create your account and redirect to the sign in page.  
    a. You should receive a notification that the account was created.
    b. NOTE: If you put in invalid information, you will remain on the create account screen and the invalid fields will be highlighted red.
